### ISSUE TITLE
st2bootstrap-deb assumes variables exist, and fails if they dont

### ISSUE THREAD

**Issue by AndyMoore111** [StackStorm/st2-packages#385]
when running st2bootstrap-deb.sh through ansible it fails with the error 'Failed on step - Configure st2 CLI config'

This is because the script assumes $HOME exists, however under ansible it doesn't seem to exist

All variables should be checked before use, and set to a default if they don't exist

fwiw i've worked around it with:

```
  if [ -z "$HOME" ];
  then
    HOME=`eval echo ~$(whoami)`
fi
```

**Comment by AndyMoore111** [comment]
the -z doesnt work with set -u

changed to 

: "${HOME:=`eval echo ~$(whoami)`}"

**Comment by emedvedev** [comment]
Fixed in #386. Will cherry-pick to `v2.1` as well.

**Comment by armab** [comment]
Re-opening as not fully solved.

This fix https://github.com/StackStorm/st2-packages/issues/386 needs to be applied for other files as well: `st2bootstrap-el6.sh` and `st2bootstrap-el7.sh`
